# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate validator_derive

Name:           rust-validator_derive
Version:        0.20.0
Release:        1%{?dist}
Summary:        Macros 1.1 implementation of #[derive(Validate)]

License:        MIT
URL:            https://crates.io/crates/validator_derive
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Macros 1.1 implementation of #[derive(Validate)].}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nightly_features-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nightly_features-devel %{_description}

This package contains library source intended for building other packages which
use the "nightly_features" feature of the "%{crate}" crate.

%files       -n %{name}+nightly_features-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Oct 22 2025 Mat Booth <mat.booth@gmail.com> - 0.20.0-1
- Initial package
