# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate pgrx-sql-entity-graph

Name:           rust-pgrx-sql-entity-graph
Version:        0.16.1
Release:        1%{?dist}
Summary:        Sql Entity Graph for pgrx

License:        MIT
URL:            https://crates.io/crates/pgrx-sql-entity-graph
Source:         %{crates_source}
# * Relax constraint to use the version shipped in Fedora
Patch10:        0001-relax-dependency-on-convert_case.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Sql Entity Graph for `pgrx`.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+no-schema-generation-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no-schema-generation-devel %{_description}

This package contains library source intended for building other packages which
use the "no-schema-generation" feature of the "%{crate}" crate.

%files       -n %{name}+no-schema-generation-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+syntax-highlighting-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+syntax-highlighting-devel %{_description}

This package contains library source intended for building other packages which
use the "syntax-highlighting" feature of the "%{crate}" crate.

%files       -n %{name}+syntax-highlighting-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * Skip tests that fail when run outside the upstream source tree
%cargo_test -- -- --skip control_file
%endif

%changelog
* Thu Oct 23 2025 Mat Booth <mat.booth@gmail.com> - 0.16.1-1
- Update to 0.16.1

* Wed Oct 22 2025 Mat Booth <mat.booth@gmail.com> - 0.15.0-1
- Initial package
