# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate pgrx-pg-sys

Name:           rust-pgrx-pg-sys
Version:        0.15.0
Release:        1%{?dist}
Summary:        Generated Rust bindings for Postgres internals, for use with 'pgrx'

License:        MIT
URL:            https://crates.io/crates/pgrx-pg-sys
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  postgresql18-server-devel
BuildRequires:  postgresql18-private-devel

%global _description %{expand:
Generated Rust bindings for Postgres internals, for use with 'pgrx'.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cshim-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cshim-devel %{_description}

This package contains library source intended for building other packages which
use the "cshim" feature of the "%{crate}" crate.

%files       -n %{name}+cshim-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pg18-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pg18-devel %{_description}

This package contains library source intended for building other packages which
use the "pg18" feature of the "%{crate}" crate.

%files       -n %{name}+pg18-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
mkdir .pgrx
echo '[configs]' >> .pgrx/config.toml
echo 'pg18 = "/usr/bin/pg_config"' >> .pgrx/config.toml

%generate_buildrequires
%cargo_generate_buildrequires -f pg18

%build
export PGRX_HOME=$(pwd)/.pgrx
%cargo_build -f pg18

%install
%cargo_install -f pg18

%if %{with check}
%check
%cargo_test -f pg18
%endif

%changelog
* Wed Oct 22 2025 Mat Booth <mat.booth@gmail.com> - 0.15.0-1
- Initial package
