# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate atomic-traits

Name:           rust-atomic-traits
Version:        0.4.0
Release:        1%{?dist}
Summary:        Traits for generic atomic operations

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/atomic-traits
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
The traits for generic atomic operations.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+atomic_access-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+atomic_access-devel %{_description}

This package contains library source intended for building other packages which
use the "atomic_access" feature of the "%{crate}" crate.

%files       -n %{name}+atomic_access-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+atomic_as_ptr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+atomic_as_ptr-devel %{_description}

This package contains library source intended for building other packages which
use the "atomic_as_ptr" feature of the "%{crate}" crate.

%files       -n %{name}+atomic_as_ptr-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+atomic_bool_fetch_not-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+atomic_bool_fetch_not-devel %{_description}

This package contains library source intended for building other packages which
use the "atomic_bool_fetch_not" feature of the "%{crate}" crate.

%files       -n %{name}+atomic_bool_fetch_not-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+atomic_from_mut-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+atomic_from_mut-devel %{_description}

This package contains library source intended for building other packages which
use the "atomic_from_mut" feature of the "%{crate}" crate.

%files       -n %{name}+atomic_from_mut-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+atomic_from_ptr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+atomic_from_ptr-devel %{_description}

This package contains library source intended for building other packages which
use the "atomic_from_ptr" feature of the "%{crate}" crate.

%files       -n %{name}+atomic_from_ptr-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+atomic_min_max-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+atomic_min_max-devel %{_description}

This package contains library source intended for building other packages which
use the "atomic_min_max" feature of the "%{crate}" crate.

%files       -n %{name}+atomic_min_max-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+atomic_mut_ptr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+atomic_mut_ptr-devel %{_description}

This package contains library source intended for building other packages which
use the "atomic_mut_ptr" feature of the "%{crate}" crate.

%files       -n %{name}+atomic_mut_ptr-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+extended_compare_and_swap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+extended_compare_and_swap-devel %{_description}

This package contains library source intended for building other packages which
use the "extended_compare_and_swap" feature of the "%{crate}" crate.

%files       -n %{name}+extended_compare_and_swap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+integer_atomics-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+integer_atomics-devel %{_description}

This package contains library source intended for building other packages which
use the "integer_atomics" feature of the "%{crate}" crate.

%files       -n %{name}+integer_atomics-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages which
use the "unstable" feature of the "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Oct 22 2025 Mat Booth <mat.booth@gmail.com> - 0.4.0-1
- Initial package
