# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate validator

Name:           rust-validator
Version:        0.20.0
Release:        1%{?dist}
Summary:        Common validation functions

License:        MIT
URL:            https://crates.io/crates/validator
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Common validation functions (email, url, length, ...) and trait - to be
used with `validator_derive`.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+card-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+card-devel %{_description}

This package contains library source intended for building other packages which
use the "card" feature of the "%{crate}" crate.

%files       -n %{name}+card-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+card-validate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+card-validate-devel %{_description}

This package contains library source intended for building other packages which
use the "card-validate" feature of the "%{crate}" crate.

%files       -n %{name}+card-validate-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+derive-devel %{_description}

This package contains library source intended for building other packages which
use the "derive" feature of the "%{crate}" crate.

%files       -n %{name}+derive-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+derive_nightly_features-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+derive_nightly_features-devel %{_description}

This package contains library source intended for building other packages which
use the "derive_nightly_features" feature of the "%{crate}" crate.

%files       -n %{name}+derive_nightly_features-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+indexmap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+indexmap-devel %{_description}

This package contains library source intended for building other packages which
use the "indexmap" feature of the "%{crate}" crate.

%files       -n %{name}+indexmap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unic-devel %{_description}

This package contains library source intended for building other packages which
use the "unic" feature of the "%{crate}" crate.

%files       -n %{name}+unic-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unic-ucd-common-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unic-ucd-common-devel %{_description}

This package contains library source intended for building other packages which
use the "unic-ucd-common" feature of the "%{crate}" crate.

%files       -n %{name}+unic-ucd-common-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+validator_derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+validator_derive-devel %{_description}

This package contains library source intended for building other packages which
use the "validator_derive" feature of the "%{crate}" crate.

%files       -n %{name}+validator_derive-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Oct 22 2025 Mat Booth <mat.booth@gmail.com> - 0.20.0-1
- Initial package
