# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate pyo3-async-runtimes-macros

Name:           rust-pyo3-async-runtimes-macros
Version:        0.25.0
Release:        1%{?dist}
Summary:        Proc Macro Attributes for pyo3-async-runtimes

License:        Apache-2.0
URL:            https://crates.io/crates/pyo3-async-runtimes-macros
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Proc Macro Attributes for `pyo3-async-runtimes`.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Oct 30 2025 Mat Booth <mat.booth@gmail.com> - 0.25.0-1
- Initial package
