# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate pgrx-macros

Name:           rust-pgrx-macros
Version:        0.16.1
Release:        1%{?dist}
Summary:        Proc Macros for 'pgrx'

License:        MIT
URL:            https://crates.io/crates/pgrx-macros
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Proc Macros for 'pgrx'.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+no-schema-generation-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no-schema-generation-devel %{_description}

This package contains library source intended for building other packages which
use the "no-schema-generation" feature of the "%{crate}" crate.

%files       -n %{name}+no-schema-generation-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Oct 23 2025 Mat Booth <mat.booth@gmail.com> - 0.16.1-1
- Update to 0.16.1

* Wed Oct 22 2025 Mat Booth <mat.booth@gmail.com> - 0.15.0-1
- Initial package
